Repository Holiday-Secret-Santa/Secret-Santa-App, pull requests merged in 2020-09, with the labels that each got.

#14 added config.yml file
  .circleci/config.yml
Labels: mvp, setup, testing

#16 Circleci project setup
  .circleci/config.yml
  .eslintrc.json
  babel.config.js
  client/package.json
  client/src/App.js
  client/src/App.test.js
  client/src/auth0-provider-with-history.js
  client/src/components/Loading/index.js
  client/src/components/LoginLink/index.js
  client/src/components/LogoutLink/index.js
  client/src/components/NavigationBar/index.js
  client/src/components/PrivateRoute/index.js
  client/src/components/ProfileLink/index.js
  client/src/components/SignupLink/index.js
  client/src/index.js
  client/src/pages/Home/index.js
  controllers/api/example.js
  controllers/api/index.js
  controllers/index.js
  controllers/tests/utils.test.js
  controllers/utils.js
  jest.config.js
  package-lock.json
  package.json
  server.js
Labels: bug, mvp, setup, testing

#19 Added ERM Diagram
  README.md
  client/src/App.js
  client/src/pages/Home/index.js
  imgs/readme/ermDiagram.png
Labels: db, documentation, mvp

#20 Update ReadMe for 2nd Review
  README.md
  imgs/readme/conceptMap.png
  imgs/readme/wireframes/addWishListItem.png
  imgs/readme/wireframes/eventDetailsGuest.png
  imgs/readme/wireframes/homepage.png
  imgs/readme/wireframes/loginAuth0.png
Labels: design, documentation, mvp

#42 Er diagram readme
  README.md
  imgs/readme/ermDiagram2.png
Labels: db, documentation

#44 Setup pages
  client/src/App.js
  client/src/components/Loading/index.js
  client/src/pages/AcceptEvent/AcceptEvent.js
  client/src/pages/AcceptEvent/AcceptEvent.test.js
  client/src/pages/AcceptEvent/style.css
  client/src/pages/CreateEvent/CreateEvent.js
  client/src/pages/CreateEvent/CreateEvent.test.js
  client/src/pages/CreateEvent/style.css
  client/src/pages/Events/Events.js
  client/src/pages/Events/Events.test.js
  client/src/pages/Events/logo.png
  client/src/pages/Events/style.css
  client/src/pages/Home/index.js
  client/src/pages/OrganizerEvent/OrganizerEvent.js
  client/src/pages/OrganizerEvent/OrganizerEvent.test.js
  client/src/pages/OrganizerEvent/style.css
  client/src/pages/ParticipantEvent/ParticipantEvent.js
  client/src/pages/ParticipantEvent/ParticipantEvent.test.js
  client/src/pages/ParticipantEvent/style.css
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/Profile.test.js
  client/src/pages/Profile/style.css
  client/src/pages/Profile/user.png
Labels: mvp, setup, testing

#45 Db event model
  config/config.json
  models/event.js
  models/index.js
  package-lock.json
  package.json
  scripts/schema.sql
  server.js
Labels: db, mvp, testing

#47 Participant Model
  models/event.js
  models/index.js
  models/participant.js
  utils/index.js
Labels: db, mvp

#50 Added gift DB model
  models/gift.js
  utils/index.js
Labels: db, mvp

#53 Landing Page
  README.md
  imgs/readme/wireframes/landingPage.png
Labels: design, documentation, frontend

#55 Nav bar
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/app.css
  client/src/components/Loading/index.js
  client/src/components/LoginLink/index.js
  client/src/components/LogoutLink/index.js
  client/src/components/NavigationBar/NavigationBar.js
  client/src/components/NavigationBar/NavigationBar.test.js
  client/src/components/NavigationBar/index.js
  client/src/components/NavigationBar/style.css
  client/src/components/ProfileLink/index.js
  client/src/components/SignupLink/index.js
  client/src/index.js
  client/src/pages/HomePage/HomePage.js
  client/src/pages/HomePage/HomePage.test.js
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/style.css
  jest.config.js
  package-lock.json
  package.json
Labels: design, frontend, mvp

#57 Created basic card component
  README.md
  client/package-lock.json
  client/package.json
  client/src/components/CardComp/index.js
Labels: frontend, mvp

#60 Details event page
  client/package.json
  client/src/App.js
  client/src/components/CardComp/index.js
  client/src/components/DetailCard/DetailCard.js
  client/src/components/DetailCard/DetailCard.test.js
  client/src/pages/ParticipantEvent/ParticipantEvent.js
  client/src/pages/ParticipantEvent/style.css
  jest.config.js
  jest.setup.js
Labels: design, frontend, mvp

#59 Create events page
  README.md
  client/package-lock.json
  client/src/app.css
  client/src/components/CardComp/index.js
  client/src/components/CardComp/style.css
  client/src/pages/Events/Events.js
  client/src/pages/Events/style.css
Labels: design, frontend, mvp

#62 52 new event form
  .eslintrc.json
  babel.config.js
  client/package-lock.json
  client/src/components/AddGuest/index.js
  client/src/components/AddGuest/style.css
  client/src/components/DateTimeInput/index.js
  client/src/components/DateTimeInput/style.css
  client/src/components/EventForm/EventForm.test.js
  client/src/components/EventForm/index.js
  client/src/components/EventForm/style.css
  client/src/components/Loading/index.js
  client/src/pages/CreateEvent/CreateEvent.js
  client/src/pages/CreateEvent/CreateEvent.test.js
  client/src/pages/Events/Events.test.js
  jest.config.js
  models/index.js
Labels: design, frontend, mvp

#63 61 event organizer view
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/ResponsiveColumn/index.js
  client/src/components/Table/index.js
  client/src/pages/Events/Events.js
  client/src/pages/OrganizerEvent/OrganizerEvent.js
  client/src/pages/OrganizerEvent/style.css
  client/src/pages/ParticipantEvent/ParticipantEvent.js
  jest.config.js
  package-lock.json
  package.json
Labels: design, frontend, mvp

#64 39 add gift page
  client/src/App.js
  client/src/components/Button/AddButton.js
  client/src/components/Button/Button.js
  client/src/components/Button/index.js
  client/src/components/CardComp/index.js
  client/src/components/CardComp/style.css
  client/src/components/FormInput/FormInput.js
  client/src/components/FormInput/FormInputNumber.js
  client/src/components/FormInput/FormInputText.js
  client/src/components/FormInput/index.js
  client/src/pages/AddGift/AddGift.js
  client/src/pages/AddGift/AddGift.test.js
  client/src/pages/AddGift/style.css
  client/src/pages/Events/Events.js
  client/src/pages/Events/style.css
Labels: design, frontend, mvp

#66 Update readme with new wireframe
  README.md
  imgs/readme/wireframes/acceptInvite.png
Labels: documentation, mvp

#69 Updated profile page
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/style.css
Labels: design, frontend, mvp

#68 38 guest accept invite
  client/src/App.js
  client/src/App.test.js
  client/src/components/Button/Button.js
  client/src/pages/AcceptEvent/AcceptEvent.js
  client/src/pages/AcceptEvent/AcceptEvent.test.js
  client/src/pages/RsvpEvent/RsvpEvent.js
  client/src/pages/RsvpEvent/RsvpEvent.test.js
  client/src/pages/RsvpEvent/style.css
  imgs/readme/wireframes/acceptInvite.png
Labels: design, frontend, mvp

#72 Added new wireframe for secret santa assignment functionality
  README.md
  imgs/readme/wireframes/eventDetailsOrganizer.png
  imgs/readme/wireframes/manageParticipants.png
Labels: design, documentation, mvp

#73 Graphql
  client/public/index.html
  graphqlSchema/schema.js
  package-lock.json
  package.json
  server.js
Labels: api, backend, graphql

#77 Exchange crud
  graphqlSchema/schema.js
  server.js
Labels: api, graphql, mvp

#84 Participant graphql
  graphqlSchema/schema.js
Labels: api, backend, mvp

#86 Frontend Improvements
  client/src/App.js
  client/src/components/FooterComp/FooterComp.js
  client/src/components/FooterComp/FooterComp.test.js
  client/src/components/FooterComp/style.css
  client/src/components/LoginLink/LoginLink.test.js
  client/src/components/NavigationBar/NavigationBar.js
  client/src/components/NavigationBar/appLogo.png
  client/src/components/NavigationBar/logo.png
  client/src/components/NavigationBar/style.css
  client/src/pages/Events/Events.js
  client/src/pages/Events/logo.png
  client/src/pages/Events/style.css
  client/src/pages/OrganizerEvent/OrganizerEvent.js
  client/src/pages/OrganizerEvent/style.css
Labels: design, frontend, mvp

#87 75 basic form inputs
  client/src/components/AddGuest/index.js
  client/src/components/AddGuest/style.css
  client/src/components/EventForm/EventForm.test.js
  client/src/components/EventForm/index.js
  client/src/components/EventForm/style.css
Labels: design, frontend, mvp

#91 Graphql Gifts Apis (CRUD)
  graphqlSchema/schema.js
  models/gift.js
  models/participant.js
  utils/index.js
Labels: api, backend, db, graphql

#74 Home page edits v1
  babel.config.js
  client/public/index.html
  client/src/components/Carousel/CarouselPage.js
  client/src/components/Carousel/imgs/gifts1-resized.jpg
  client/src/components/Carousel/imgs/gifts4-resized.jpg
  client/src/components/Carousel/imgs/hohoho-resized.jpg
  client/src/components/Carousel/style.css
  client/src/components/HomePageImgs/HomePageImgs.js
  client/src/components/HomePageImgs/imageData.json
  client/src/components/HomePageImgs/style.css
  client/src/components/WelcomeMessage/WelcomeMsg.js
  client/src/components/WelcomeMessage/style.css
  client/src/pages/HomePage/HomePage.js
  client/src/pages/HomePage/style.css
  package.json
Labels: design, frontend, mvp

#93 78 add modal comp
  client/src/components/ModalPopUp/ModalPopUp.js
  client/src/components/ModalPopUp/ModalPopUp.test.js
  client/src/pages/OrganizerEvent/OrganizerEvent.js
  client/src/pages/OrganizerEvent/style.css
Labels: design, frontend, mvp

#94 Graphql Apis Assign
  client/src/components/Carousel/CarouselPage.js
  client/src/components/Carousel/style.css
  client/src/components/FooterComp/FooterComp.js
  client/src/components/FooterComp/style.css
  client/src/components/HomePageImgs/HomePageImgs.js
  client/src/components/HomePageImgs/style.css
  client/src/components/WelcomeMessage/WelcomeMsg.js
  client/src/components/WelcomeMessage/style.css
  client/src/pages/HomePage/HomePage.js
  graphqlSchema/schema.js
Labels: api, backend, frontend, mvp

#95 Fix graphql schema
  graphqlSchema/schema.js
Labels: api, backend, bug

#97 Auto Assign Participant
  graphqlSchema/schema.js
Labels: api, backend, db, mvp

#100 99 list events
  client/src/actions/graphql.api.js
  client/src/actions/graphql.api.test.js
  client/src/actions/graphql.queries.js
  client/src/actions/graphql.queries.test.js
  client/src/pages/CreateEvent/CreateEvent.js
  client/src/pages/CreateEvent/CreateEvent.test.js
Labels: mvp

#101 99 list events
  client/src/actions/graphql.api.js
  client/src/actions/graphql.api.test.js
  client/src/actions/graphql.queries.js
  client/src/actions/graphql.queries.test.js
  client/src/components/DetailCard/DetailCard.js
  client/src/pages/Events/Events.js
  client/src/pages/Events/Events.test.js
  graphqlSchema/schema.js
Labels: api, backend, db, frontend, mvp

#102 Added UI functionality to create participant
  babel.config.js
  client/package-lock.json
  client/package.json
  client/src/actions/graphql.api.js
  client/src/actions/graphql.api.test.js
  client/src/actions/graphql.queries.js
  client/src/actions/graphql.queries.test.js
  client/src/components/FormInput/FormInputText.js
  client/src/components/ModalPopUp/ModalPopUp.js
  client/src/components/ModalPopUp/ModalPopUp.test.js
  client/src/pages/OrganizerEvent/OrganizerEvent.js
  client/src/pages/OrganizerEvent/OrganizerEvent.test.js
  client/src/pages/ParticipantEvent/ParticipantEvent.js
  client/src/pages/ParticipantEvent/ParticipantEvent.test.js
  client/src/pages/Profile/style.css
  config/config.json
  graphqlSchema/schema.js
Labels: api, backend, db, mvp

#104 Render Participant Info
  client/src/actions/graphql.api.js
  client/src/actions/graphql.api.test.js
  client/src/actions/graphql.queries.js
  client/src/actions/graphql.queries.test.js
  client/src/components/NavigationBar/NavigationBar.js
  client/src/components/NavigationBar/NavigationBar.test.js
  client/src/pages/OrganizerEvent/OrganizerEvent.js
  client/src/pages/OrganizerEvent/OrganizerEvent.test.js
Labels: api, backend, db, frontend, mvp

#106 Rendered Event Info on Organizer Event Page
  client/src/actions/graphql.api.js
  client/src/actions/graphql.api.test.js
  client/src/actions/graphql.queries.js
  client/src/actions/graphql.queries.test.js
  client/src/pages/OrganizerEvent/OrganizerEvent.js
  client/src/pages/OrganizerEvent/OrganizerEvent.test.js
Labels: api, backend, db, frontend, mvp

#108 Dynamically Add Participants
  client/src/pages/OrganizerEvent/OrganizerEvent.js
  client/src/pages/OrganizerEvent/OrganizerEvent.test.js
Labels: backend, frontend, mvp

#110 Delete event
  client/src/App.js
  client/src/actions/graphql.api.js
  client/src/actions/graphql.api.test.js
  client/src/actions/graphql.queries.js
  client/src/actions/graphql.queries.test.js
  client/src/pages/Events/Events.js
  client/src/pages/Events/Events.test.js
  client/src/pages/OrganizerEvent/OrganizerEvent.js
  config/config.json
Labels: api, backend, frontend, mvp

#112 83 random assign
  client/src/actions/graphql.api.js
  client/src/actions/graphql.api.test.js
  client/src/actions/graphql.queries.js
  client/src/actions/graphql.queries.test.js
  client/src/components/DetailCard/DetailCard.js
  client/src/components/ModalPopUp/ModalPopUp.js
  client/src/pages/OrganizerEvent/OrganizerEvent.js
  client/src/pages/OrganizerEvent/OrganizerEvent.test.js
  client/src/pages/RsvpEvent/RsvpEvent.js
  graphqlSchema/schema.js
  models/participant.js
Labels: api, backend, db, frontend

#113 Designed basic email template
  config/config.json
  package-lock.json
  package.json
  utils/inviteEmail.js
Labels: backend, mvp

#116 Enable email to be sent to newly added participants
  graphqlSchema/schema.js
  utils/inviteEmail.js
Labels: api, backend, mvp

#117 111 render gift to participant
  client/src/actions/graphql.api.js
  client/src/actions/graphql.queries.js
  client/src/pages/AddGift/AddGift.js
  client/src/pages/ParticipantEvent/ParticipantEvent.js
  client/src/pages/ParticipantEvent/ParticipantEvent.test.js
  config/config.json
  graphqlSchema/schema.js
  utils/index.js
Labels: api, backend, db, frontend

#123 Modified email link in RSVP email
  config/config.json
  graphqlSchema/schema.js
  utils/inviteEmail.js
Labels: api, backend, db, mvp

#125 76 ui
  client/src/app.css
  client/src/components/FooterComp/style.css
  client/src/components/Link/LoginLink.js
  client/src/components/Link/LogoutLink.js
  client/src/components/NavigationBar/NavigationBar.js
  client/src/components/NavigationBar/NavigationBar.test.js
  client/src/components/NavigationBar/style.css
  client/src/pages/Events/style.css
  config/config.json
Labels: design, frontend
