Repository Holiday-Secret-Santa/Secret-Santa-App, pull requests merged in 2020-08, with the labels that each got.

#2 First draft of ReadMe proposal
  README.md
  imgs/readme/appLogo.png
  imgs/readme/conceptMap.png
Labels: documentation

#9 Sequence Diagrams
  README.md
  imgs/readme/create-event.svg
  imgs/readme/guest-assign-manual.svg
  imgs/readme/guest-assign-system.svg
  imgs/readme/guest-gift-ideas.svg
  imgs/readme/invite-guest.svg
  imgs/readme/track-invitations.svg
Labels: design, documentation, mvp

#10 Added Initial Wireframes and API Info
  README.md
  imgs/readme/appLogo.png
  imgs/readme/wireframes/addWishListItem.png
  imgs/readme/wireframes/createEvent.png
  imgs/readme/wireframes/eventDashboard.png
  imgs/readme/wireframes/eventDetailsGuest.png
  imgs/readme/wireframes/eventDetailsOrganizer.png
  imgs/readme/wireframes/homepage.png
  imgs/readme/wireframes/homepageImg.jpg
  imgs/readme/wireframes/loginAuth0.png
Labels: documentation, mvp

#12 Project Setup with Auth0
  .gitignore
  README.md
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/App.test.js
  client/src/auth0-provider-with-history.js
  client/src/components/Loading/index.js
  client/src/components/LoginLink/index.js
  client/src/components/LogoutLink/index.js
  client/src/components/NavigationBar/index.js
  client/src/components/NavigationBar/logo.png
  client/src/components/NavigationBar/style.css
  client/src/components/PrivateRoute/index.js
  client/src/components/ProfileLink/index.js
  client/src/components/SignupLink/index.js
  client/src/index.js
  client/src/pages/Home/index.js
  client/src/pages/Home/logo.png
  client/src/pages/Home/style.css
  controllers/api/example.js
  controllers/api/index.js
  controllers/index.js
  package-lock.json
  package.json
  scripts/schema.sql
  scripts/seedDB.js
  server.js
Labels: auth0, mvp, setup
